#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <namespace> <resource_type>"
  exit 1
fi

if [[ ! $2 =~ ^(node|pod)$ ]]; then
  echo "Invalid resource type. Supported resource types: node, pod"
  exit 1
fi

NAMESPACE=$1
RESOURCE_TYPE=$2

kubectl top "$RESOURCE_TYPE" -n "$NAMESPACE" | tail -n +2 | while read -r line
do
  NAME=$(echo "$line" | awk '{print $1}')
  CPU=$(echo "$line" | awk '{print $2}')
  MEMORY=$(echo "$line" | awk '{print $3}')

  printf "Resource: %-8s | Namespace: %-20s | Name: %-50s | CPU: %-5s | Memory: %-5s\n" \
    "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
done
